#version of open api
openapi: 3.0.0
#api details
info:
  title: Jobs API
  description: API documentation for user authentication and job management
  version: 1.0.0
#the base url
servers:
  - url: http://localhost:8000
    description: Local server
  - url: https://jobsapi-lfz8.onrender.com
    description: Production server 
#makeup of the api
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  #models
  #emaxple optional
  schemas:
    user:
      type: object
      properties:
        email:
          type: string
          example: "user@example.com"
        password:
          type: string
          example: "securepassword"

    jobs:
      type: object
      properties:
        title:
          type: string
          example: "Software Engineer"
        description:
          type: string
          example: "Develop and maintain web applications."
        company:
          type: string
          example: "TechCorp"
        salary:
          type: integer
          example: 70000
#define routes
paths:
  /register:
    post:
      summary: Register a new user
      #
      tags: [user]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        201:
          description: User registered successfully
        400:
          description: Invalid request data

  /login:
    post:
      summary: User login
      tags: [user]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "securepassword"
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: "your-jwt-token-here"
        401:
          description: Unauthorized

  /logout:
    get:
      summary: User logout
      tags: [user]
      security:
        - BearerAuth: []
      responses:
        200:
          description: Logout successful
        401:
          description: Unauthorized

  /jobs:
    get:
      summary: Get all jobs
      tags: [jobs]
      responses:
        200:
          description: List of jobs retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/jobs"
    post:
      summary: Add a new job
      tags: [jobs]
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/jobs"
      responses:
        201:
          description: Job added successfully
        401:
          description: Unauthorized

  /jobs/{id}:
    get:
      summary: Get a job by ID
      tags: [jobs]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Job ID
      responses:
        200:
          description: Job found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Jobs"
        404:
          description: Job not found

    put:
      summary: Update a job
      tags: [jobs]
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Job ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/jobs"
      responses:
        200:
          description: Job updated successfully
        401:
          description: Unauthorized
        404:
          description: Job not found

    delete:
      summary: Delete a job
      tags: [jobs]
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: Job ID
      responses:
        200:
          description: Job deleted successfully
        401:
          description: Unauthorized
        404:
          description: Job not found

  /user/jobs:
    get:
      summary: Get all jobs for a user
      tags: [jobs]
      security:
        - BearerAuth: []
      responses:
        200:
          description: Get jobs for the user successfully
        401:
          description: Unauthorized
